"""reconcile schema with models

Revision ID: 50c8b65617d6
Revises: add_audit_logs
Create Date: 2026-08-04 17:10:12.472629+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50c8b65617d6"
down_revision: Union[str, None] = "add_audit_logs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="pipelinestatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("current_step_name", sa.String(length=255), nullable=True),
        sa.Column("step_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_step", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_pipeline_id"), "pipeline_runs", ["pipeline_id"], unique=False
    )
    op.add_column("analyses", sa.Column("current_step", sa.String(length=255), nullable=True))
    op.add_column("analyses", sa.Column("total_steps", sa.Integer(), nullable=False))
    op.alter_column(
        "analyses",
        "analysis_type",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Enum(
            "single_omics",
            "multi_omics",
            "integration",
            "differential_expression",
            "pathway",
            "clustering",
            "survival",
            name="analysistype",
            native_enum=False,
            length=50,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "analyses",
        "omics_types",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        postgresql_using="to_jsonb(omics_types)",
    )
    op.alter_column(
        "analyses", "progress", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "analyses",
        "parameters",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "analyses",
        "input_datasets",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        postgresql_using="to_jsonb(input_datasets)",
    )
    op.alter_column(
        "analyses",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.add_column("analysis_results", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column("analysis_results", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "analysis_results",
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "analysis_results",
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("analysis_results", sa.Column("file_type", sa.String(length=50), nullable=True))
    op.add_column("analysis_results", sa.Column("file_size", sa.BigInteger(), nullable=True))
    op.alter_column(
        "analysis_results",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.add_column(
        "datasets",
        sa.Column(
            "omics_type",
            sa.Enum(
                "genomics",
                "transcriptomics",
                "proteomics",
                "metabolomics",
                "epigenomics",
                "pharmacogenomics",
                name="omicstype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
    )
    op.add_column("datasets", sa.Column("data_format", sa.String(length=50), nullable=True))
    op.add_column(
        "datasets",
        sa.Column(
            "status",
            sa.Enum(
                "uploading",
                "processing",
                "ready",
                "archived",
                "error",
                name="datasetstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
    )
    op.add_column("datasets", sa.Column("sample_count", sa.Integer(), nullable=True))
    op.add_column("datasets", sa.Column("feature_count", sa.Integer(), nullable=True))
    op.add_column("datasets", sa.Column("total_size", sa.BigInteger(), nullable=True))
    op.add_column("datasets", sa.Column("source", sa.String(length=255), nullable=True))
    op.add_column("datasets", sa.Column("source_id", sa.String(length=255), nullable=True))
    op.add_column("datasets", sa.Column("qc_passed", sa.Boolean(), nullable=True))
    op.add_column(
        "datasets", sa.Column("qc_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "datasets",
        sa.Column("preprocessing_applied", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "datasets", sa.Column("normalization_method", sa.String(length=100), nullable=True)
    )
    op.add_column("datasets", sa.Column("storage_path", sa.String(length=500), nullable=True))
    op.add_column("datasets", sa.Column("storage_type", sa.String(length=50), nullable=False))
    op.add_column(
        "datasets",
        sa.Column("clinical_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "datasets",
        sa.Column("sample_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "datasets",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("datasets", "uploaded_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "datasets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.add_column("pipelines", sa.Column("version", sa.String(length=50), nullable=False))
    op.add_column(
        "pipelines",
        sa.Column("omics_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "pipelines",
        sa.Column("default_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("pipelines", sa.Column("timeout_seconds", sa.Integer(), nullable=True))
    op.add_column("pipelines", sa.Column("max_retries", sa.Integer(), nullable=False))
    op.add_column(
        "pipelines", sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column("pipelines", sa.Column("author", sa.String(length=255), nullable=True))
    op.add_column("pipelines", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("pipelines", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.alter_column(
        "pipelines", "pipeline_type", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("pipelines", "is_template", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("pipelines", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "pipelines",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.add_column("projects", sa.Column("project_type", sa.String(length=100), nullable=False))
    op.add_column(
        "projects",
        sa.Column("omics_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("projects", sa.Column("visibility", sa.String(length=50), nullable=False))
    op.add_column(
        "projects",
        sa.Column(
            "status",
            sa.Enum(
                "active", "archived", "deleted", name="projectstatus", native_enum=False, length=50
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "projects", sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "projects", sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "projects",
        sa.Column("collaborators", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.alter_column(
        "projects",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        postgresql_using="to_jsonb(tags)",
    )
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column(
        "users",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "roles",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "permissions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "settings",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::json"),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "permissions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "roles",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
        postgresql_using="translate(tags::text, '[]\"', '{}')::varchar[]",
    )
    op.drop_column("projects", "collaborators")
    op.drop_column("projects", "metadata")
    op.drop_column("projects", "config")
    op.drop_column("projects", "status")
    op.drop_column("projects", "visibility")
    op.drop_column("projects", "omics_types")
    op.drop_column("projects", "project_type")
    op.alter_column(
        "pipelines",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column("pipelines", "owner_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("pipelines", "is_template", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "pipelines", "pipeline_type", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("pipelines", "is_public")
    op.drop_column("pipelines", "is_active")
    op.drop_column("pipelines", "author")
    op.drop_column("pipelines", "tags")
    op.drop_column("pipelines", "max_retries")
    op.drop_column("pipelines", "timeout_seconds")
    op.drop_column("pipelines", "default_parameters")
    op.drop_column("pipelines", "omics_types")
    op.drop_column("pipelines", "version")
    op.alter_column(
        "datasets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column("datasets", "uploaded_by", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "datasets", "metadata", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True
    )
    op.drop_column("datasets", "sample_metadata")
    op.drop_column("datasets", "clinical_data")
    op.drop_column("datasets", "storage_type")
    op.drop_column("datasets", "storage_path")
    op.drop_column("datasets", "normalization_method")
    op.drop_column("datasets", "preprocessing_applied")
    op.drop_column("datasets", "qc_metrics")
    op.drop_column("datasets", "qc_passed")
    op.drop_column("datasets", "source_id")
    op.drop_column("datasets", "source")
    op.drop_column("datasets", "total_size")
    op.drop_column("datasets", "feature_count")
    op.drop_column("datasets", "sample_count")
    op.drop_column("datasets", "status")
    op.drop_column("datasets", "data_format")
    op.drop_column("datasets", "omics_type")
    op.alter_column(
        "analysis_results",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("analysis_results", "file_size")
    op.drop_column("analysis_results", "file_type")
    op.drop_column("analysis_results", "metrics")
    op.drop_column("analysis_results", "summary")
    op.drop_column("analysis_results", "description")
    op.drop_column("analysis_results", "name")
    op.alter_column(
        "analyses",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "input_datasets",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
        postgresql_using="translate(input_datasets::text, '[]\"', '{}')::varchar[]",
    )
    op.alter_column(
        "analyses",
        "parameters",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "analyses", "progress", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "analyses",
        "omics_types",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
        postgresql_using="translate(omics_types::text, '[]\"', '{}')::varchar[]",
    )
    op.alter_column(
        "analyses",
        "analysis_type",
        existing_type=sa.Enum(
            "single_omics",
            "multi_omics",
            "integration",
            "differential_expression",
            "pathway",
            "clustering",
            "survival",
            name="analysistype",
            native_enum=False,
            length=50,
        ),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("analyses", "total_steps")
    op.drop_column("analyses", "current_step")
    op.drop_index(op.f("ix_pipeline_runs_pipeline_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
