apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moas-ingress
  namespace: multi-omics
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.multi-omics.example.com
        - dashboard.multi-omics.example.com
      secretName: moas-tls
  rules:
    - host: api.multi-omics.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moas-api
                port:
                  number: 8000
    - host: dashboard.multi-omics.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moas-dash
                port:
                  number: 8050
